/**
 * Test blueprint strings generated by encoding known JSON structures.
 *
 * These are structurally valid Factorio 2.0 blueprint strings that can be
 * decoded, verified, and round-tripped through encode/decode.
 */

/**
 * Simple belt layout: 4 transport belts in a line heading east.
 * Factorio 2.0.28
 */
export const SIMPLE_BELT_LINE =
  "0eNqVztsKgzAMBuB3yXU3tFrBvsqQ4SGMgKbS1jGRvvuq3gy2gV6FJPxfskDTTzhaYg96" +
  "AfI4gP6YCXiidWQYtCpkmZelUlIVmUwEUGvYgb7FGHf4Ap0KcPTgul8prgeMlLc1u9FYf2" +
  "mw9xBCJQDZkyfcs1sz33kaGrSb8TspYDQuxtZXFojXkqsSMG81COjIYrtv8yC+WHmYTc+w" +
  "2WFWnmHzw2z2n61CeAMyRZ3u";

/**
 * Arithmetic combinator wired to a constant combinator with red wire.
 * Demonstrates the 2.0 flat wire format.
 * Factorio 2.0.28
 */
export const COMBINATOR_CIRCUIT =
  "0eNqFkdFugzAMRf/Fj1M6ASuV4FcqhAK4qyVIUOJ0qxD/Pge6dRtTBy+J43tybzxB0wcc" +
  "HRmGcgJiHKD8VlNwQefJGijzQ1bsiyLPs/zwkiUKqLXGQ3kUmenwHcpUgadXo/uIMnpAQW" +
  "lHfB6Qqd21dmjIaLYO5rlSgIaJCVfEsrnWJgwNugX1EKBgtF7U0dgEcnfynCu4inBW0JHD" +
  "dj3bKxCX7GxfN3jWFxKtCO7QWo67BSQ+JjiR81xvUpCzZjf2mhGEb0d0euXDk1jxGCGR5F" +
  "nHh8ykJ/AY/iHJpzbJRXtr/eQ9zJ3dckt+cfZXVvJ17GYXcLH6lfW+/jHCE/UsM/9V3dqP" +
  "t4WYNk3mSv5lpm/y9FF6TFWqMpVWUv8AV1/Rpg==";

/**
 * Blueprint book containing two simple blueprints (belt section + inserter pair).
 * Factorio 2.0.28
 */
export const SIMPLE_BLUEPRINT_BOOK =
  "0eNqtkE9rwzAMxb9K0NkbbVYX4mNvuw222xjBWXUQS+wgq2Ul5LtPSbOMsT8ttGAwtvR+" +
  "T3odVPUOW6YgZRXjG7gOSLAB91W4GQsG9siJYgBn13mxKgprc7u+yxcG/KvQHksKW3wHpx" +
  "+1r7BWxhMmyTZH+cxL4J7VZW6eC7+Z/+v7abPBWrJH1Cm0zQAGISE8+oyPQxl2TYUMbmkg" +
  "+AZVJOxDaiPrfipXWRuTygajDobJbq2Bw3j3BrbEE9+tevMDm5+NXf6NfekH8hSMDnp5MP" +
  "chIQty9uCJz06GJtXVMjkN1FS+AxdDGno+ABXM2+c=";
